// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXR1W_0uVhFgfaUNNxMgnHQO8SwhHGCog',
    appId: '1:827022100880:web:ba1a65dbd6d008788e8b15',
    messagingSenderId: '827022100880',
    projectId: 'notesapp-khodesmith',
    authDomain: 'notesapp-khodesmith.firebaseapp.com',
    storageBucket: 'notesapp-khodesmith.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyvgrmJctvd8eSPOqWP0-mNJTidY7Zws',
    appId: '1:827022100880:android:881279059c8fbe2e8e8b15',
    messagingSenderId: '827022100880',
    projectId: 'notesapp-khodesmith',
    storageBucket: 'notesapp-khodesmith.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB653OTr0ovKOXDzmlmVS6R47yVqqfjLrw',
    appId: '1:827022100880:ios:3416a8ef4b07ead58e8b15',
    messagingSenderId: '827022100880',
    projectId: 'notesapp-khodesmith',
    storageBucket: 'notesapp-khodesmith.appspot.com',
    iosClientId: '827022100880-9lpm7bg92lo9t2lvj9mi15rqhb6eufll.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB653OTr0ovKOXDzmlmVS6R47yVqqfjLrw',
    appId: '1:827022100880:ios:3416a8ef4b07ead58e8b15',
    messagingSenderId: '827022100880',
    projectId: 'notesapp-khodesmith',
    storageBucket: 'notesapp-khodesmith.appspot.com',
    iosClientId: '827022100880-9lpm7bg92lo9t2lvj9mi15rqhb6eufll.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );
}
